### ISSUE TITLE
Please upgrade to Flutter 2.0 null safety

### ISSUE THREAD

**Issue by ghost** [zlumyo/dart_numerics#3]
This issue prevents the dart_numerics package from being used when using sound null safety.

The only real issue preventing dart_numerics from is this line:
https://github.com/zlumyo/dart_numerics/blob/master/lib/src/precision.dart#L28

Original:
final double doublePrecision = pow(2, -doubleWidth);

'dart migrate' flagged issue:
final double doublePrecision = pow(2, -doubleWidth) as double;

However, adding that downcast causes quite a few unit tests to fail.

**Comment by yych42** [comment]
That's not a problem with null safety. See #2. 

I didn't fix this problem, but sent out a pull request anyway: #4

**Comment by zlumyo** [comment]
I think this one can be closed. @yych42 's explanation is right.
